services:
  agroflowers-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_API_BASE_URL: http://localhost/api
        PUBLIC_KEYCLOAK_URL: http://localhost/auth
        PUBLIC_KEYCLOAK_REALM: agroflowers-realm
        PUBLIC_KEYCLOAK_CLIENT_ID: agroflowers-web
        PUBLIC_USE_MOCKS: "true"
    container_name: agroflowers-frontend
    restart: unless-stopped
    ports:
      - "8095:80"
